const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const axios = require('@zeppos/zeus-cli/node_modules/axios').default || require('@zeppos/zeus-cli/node_modules/axios');

/**
 * Random Token Generator
 * @param {number} targetLength
 */
function generateRandomToken(targetLength = 250) {
    // Generate the base 64 random token (133% than mines)
    const byteLength = Math.ceil(targetLength * 0.75);
    return crypto.randomBytes(byteLength)
        .toString('base64')
        .replace(/\+/g, '-') // Replace to URL-safe
        .replace(/\//g, '_')
        // .substring(0, targetLength); // cut to like mine's token (Not need on Amazfit Watchface site)
}

async function downloadFile(targetUrl, savePath) {
    // Token generator
    fakeToken = generateRandomToken(255);

    // You can put your real token here (Use Zepp's developer tool scan the QR code by the post url generated by
    // https://posttestserver.dev/ and replace the "https" to "zpkd1", like zpkd1://posttestserver.dev/p/<roomcode>/post)
    // fakeToken = "";
    
    console.log(`Token preview: ${fakeToken.substring(0, 30)}...`);

    const headers = {
        'accept-encoding': 'gzip',
        'apptoken': fakeToken, // Use random token
        'connection': 'Keep-Alive',
        'user-agent': 'Dart/3.1 (dart:io)',
        'accept': null 
    };

    try {
        console.log(`Ready to download: ${targetUrl}`);
        
        const response = await axios({
            method: 'get',
            url: targetUrl,
            responseType: 'stream',
            headers: headers
        });


        const finalPath = savePath || (path.basename(new URL(targetUrl).pathname) || 'download_file.bin');
        const writer = fs.createWriteStream(finalPath);

        response.data.pipe(writer);

        // Stuck the process
        return new Promise((resolve, reject) => {
        writer.on('finish', () => {
            console.log(`✅ File fully written to: ${savePath}`);
            resolve(savePath);
        });
        writer.on('error', (err) => {
            console.error('Write Failed:', err);
            reject(err);
        });
    });

    } catch (error) {
        if (error.response) {
            console.error(`Access Denied: [${error.response.status}]:`, error.response.statusText);
        } else {
            console.error('Got Error:', error.message);
        }
    }
}

module.exports = { downloadFile };

if (require.main === module) {
    const url = process.argv[2];
    if (url) {
        downloadFile(url.replace("zpkd1://", "https://"));
    } else {
        console.log('Please provides the URL.');
    }
}